# Generated by Django 5.0.2 on 2024-03-03 14:03

from django.db import migrations, models

def create_default_coins(apps, schema_editor):
    Coin = apps.get_model('convert', 'Coin')
    Coin.objects.create(name='USD', abbreviation='USD')
    Coin.objects.create(name='BRL', abbreviation='BRL')
    Coin.objects.create(name='EUR', abbreviation='EUR')
    Coin.objects.create(name='bitcoin', abbreviation='BTC')
    Coin.objects.create(name='ethereum', abbreviation='ETH')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
            },
        ),
        migrations.RunPython(create_default_coins),
    ]
